<a href="https://colab.research.google.com/github/jinsumin81/2024-intro-DA-code/blob/main/w05_numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
from numpy import array

a = array([3,4,5])
b = array([8,7,6])
a+b

array([11, 11, 11])

In [3]:
from numpy import array
a = array([3,4,5,7])
b = array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
from numpy import array
a=array([3,4,5])
a

In [4]:
b=2
b

2

In [5]:
a+b

array([5, 6, 7, 9])

In [6]:
from numpy import array
A=array([[1,2,3],[1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
A+2

array([[3, 4, 5],
       [3, 4, 5]])

In [8]:
from numpy import arange

x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y = arange(-1,2)
y

array([-1,  0,  1])

In [10]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [11]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [12]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [14]:
x/y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [15]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [16]:
from numpy import arange
x = arange(1,4)
x

array([1, 2, 3])

In [17]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [18]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [19]:
x-y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [20]:
from numpy import arange
x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [21]:
y = arange(1,3)
y

array([1, 2])

In [22]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [23]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [24]:
from numpy import array
x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [25]:
a = x[None,:]
a

array([[ 0, 10, 20, 30]])

In [26]:
a = x[np.newaxis,:]
a

array([[ 0, 10, 20, 30]])

In [27]:
a = x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [28]:
from numpy import array
b=array([1,2,3])
b

array([1, 2, 3])

In [29]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [30]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [31]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [33]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [34]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [35]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [36]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [37]:
x[0,1]

1

In [38]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [39]:
x[[0],[1]]

array([1])

In [40]:
x[:,[5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [41]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [42]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [43]:
x[[1,3],[2,2]]

array([10, 26])

In [44]:
x[[1,3],[2]]

array([10, 26])

In [45]:
x[[1,3],[3,3]]

array([11, 27])

In [46]:
x[[1,3],[3]]

array([11, 27])

In [47]:
from numpy import array
x[array([0,2,4]), array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [48]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [49]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [50]:
print(x[[2]])
print(x[[2,3]])

[[16 17 18 19 20 21 22 23]]
[[16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [51]:
from numpy import arange
a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [52]:
a[2:3,3:7]

array([[19, 20, 21, 22]])

In [53]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [54]:
a[arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [55]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [56]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [57]:
import numpy as np

a= np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
b = np.arange(6, 12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
c = np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [61]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [62]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [63]:
d = np.array([100, 200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [64]:
d = np.array([100, 200, 300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [65]:
import numpy as np

x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [66]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
b = np.arange(10, 19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [70]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [71]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [72]:
np.hstack((np.arange(3), np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [73]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [74]:
b = np.arange(10, 22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [75]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [76]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [80]:
x = np.array([1,2,3])
y =np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [81]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [82]:
y[:,np.newaxis]

array([[10],
       [20],
       [30]])

In [83]:
x = np.array([1,2,3])
y = np.array([10, 20, 30])
np.column_stack((x[:,np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [84]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [85]:
np.column_stack == np.hstack

False

In [92]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [93]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [94]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [95]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [96]:
x = np.array([1,2,3])
y = np.array([10, 20, 30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [97]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [98]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [99]:
x = np.array([1,2,3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [100]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [101]:
np.column_stack == np.hstack

False

In [102]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
b = np.arange(10, 22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [104]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [106]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [108]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [109]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [110]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [111]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [112]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [113]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [114]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [118]:
z = np.arange(20, 24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [119]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [120]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [121]:
np.concatenate((x, y), axis = 1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [122]:
np.concatenate((x,y,z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [123]:
np.concatenate((x,y), axis = None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [124]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [125]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [126]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [128]:
np.stack((a,b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
y = np.arange(10, 16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [132]:
z = np.arange(20, 26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [133]:
ax0 = np.stack((x,y,z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [134]:
ax0.shape

(3, 2, 3)

In [135]:
ax1 = np.stack((x, y ,z), axis =1)

In [136]:
ax0.shape

(3, 2, 3)

In [137]:
ax2 = np.stack((x, y ,z), axis =2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [138]:
ax0.shape

(3, 2, 3)

In [139]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [141]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [142]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [143]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [144]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [145]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])